### ISSUE TITLE
SD card, GY-521 voltage. VSYS and VBUS.

### ISSUE THREAD

**Issue by Rudo2204** [kiwih/kiwikit-pico-baseboard#1]
Thank you for putting up a nicely done breakout board.
I have a question though: shouldn't SD card and GY-521 breakout voltage input pin use the 3.3V line instead of VSYS? These devices often uses 3.3V rather than 5V.
Also naming VSYS as 5V seems strange to me. VSYS can be anything from 1.8V to 5.5V according to the datasheet.
If this board is meant to be used with microUSB cable then using VBUS to get a reliable 5V source seems more reasonable.

**Comment by kiwih** [comment]
Thanks for your feedback!
My GY-521 boards have their own voltage regulator onboard to step them down to 3.3V. 
The reason VSYS can be lots of different voltages is exactly why we label it VSYS! 
As to using VSYS as the voltage bus, the document https://datasheets.raspberrypi.org/pico/pico-datasheet.pdf describes the power chain (section 4.5 and so on). My logic was 

1. I want to be able to use the USB port to power the board without a power supply, which neccessitates drawing power out either via VBUS or VSYS,
2. However I also want to protect the upstream USB device - I don't want to accidentally feed voltage backwards into my USB port on my PC if the board is powered externally, so I want the diode to prevent this

This leads towards using VSYS as the voltage bus as it can safely be used to either take power from the USB port to feed the Pico and the dev board, or be used to inject power externally when the USB is unplugged.

**Comment by Rudo2204** [comment]
Thank you for your insights to the design. I have checked and it is indeed that both devices can safely be powered with a 5V supply. I have a mfrc522 module that I want to try out with this dev board. It only allows a maximum input voltage of 3.6V so I will be careful when I use that!
I have just one more question to test if I have the correct understanding regarding powering the board externally via VSYS: because we use it as our voltage bus, so in order to both power the pico and the dev board correctly I would have to supply 5V to this pin using the J1 connector on the dev board. It seems like I cannot go lower than 4.5V because of the SD card module requirement or higher than 5.5V because of the pico limit. Is this correct?

**Comment by kiwih** [comment]
Those seem like reasonable assumptions to make, yes. It depends on the tolerance of your SD card board as well. I have SD card boards that will go as low as 3.3V. I'm not sure what the upper limit on the Pico is, but certainly the LDO on it will start to get hot if it gets too far beyond 5.5V or so.

**Comment by Rudo2204** [comment]
Thanks again for answering all my noob questions. I'm gonna order some boards off JLCPCB and see how it goes!

**Comment by kiwih** [comment]
No worries, good luck!
